#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/freq_mod_spheres.jar:$APPDIR/lib/core.jar:$APPDIR/lib/beads.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_share.jar" freq_mod_spheres
